config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/ask', to: 'questions#ask'
  get '/answer', to: 'questions#answer'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def ask 
  end

  def answer
    @question = params[:question]
    @answer = if @question.downcase == 'i am going to work'
                'Great!'
              elsif @question.end_with? '?'
                'Silly question, get dressed and go to work!'
              else
                "I don't care, get dressed and go to work!"
              end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsStupidCoaching</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/answer.html.erb
<div class="container">
<h1>Stupid Coaching</h1>

<div class="you">
  <ul>
    <%= @question %>
    <p><em>- You</em></p>
  </ul>
</div>
<div class="coach">
  <ul>
    <strong><%= @answer %></strong>
    <p><i>- Your coach</i></p>
  </ul>
<%= link_to "Ask a new question", ask_path %>
</div>
</div>

app/views/questions/ask.html.erb
<div class="main-container">

  <h1>Stupid Coaching!</h1>
  <h2>Ask your coach</h2>

  <form action="/answer">
    <input type="text" name="question" placeholder="ask me" id="ask">
    <input type="submit" value="Ask!" id="btn">
  </form>

</div>